"""Streamlit dashboard: patient view and physiotherapist view (proposal section 10).

Run:  streamlit run physio/dashboard/app.py
Talks to the FastAPI backend at PHYSIO_API_URL (default http://localhost:8000).
"""
from __future__ import annotations

import os

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import requests
import streamlit as st

API = os.environ.get("PHYSIO_API_URL", "http://localhost:8000").rstrip("/")
st.set_page_config(page_title="Home Physiotherapy Assistant", page_icon="🏃", layout="wide")


def api(method: str, path: str, **kw):
    r = requests.request(method, f"{API}{path}", timeout=600, **kw)
    if r.status_code >= 400:
        try:
            detail = r.json().get("detail", r.text)
        except Exception:  # noqa: BLE001
            detail = r.text
        raise RuntimeError(f"{r.status_code}: {detail}")
    return r.json()


def disclaimer():
    st.caption("This tool reports measurements and model estimates from video. It is not a medical device and does "
               "not replace assessment by a qualified physiotherapist.")


def show_session(s: dict, show_feedback: bool = True):
    if s["status"] != "analyzed":
        st.error(f"Unable to analyze: {s.get('unable_reason')}")
        if show_feedback and s.get("feedback"):
            st.info(s["feedback"])
        return
    c1, c2, c3 = st.columns(3)
    c1.metric("Detected exercise", s["exercise_name"], f"confidence {s['exercise_confidence']:.0%}")
    c2.metric("Movement-quality score", f"{s['quality_score']:.0f} / 100" if s.get("quality_score") is not None else "n/a")
    c3.metric("Needs review", "Yes" if s["needs_review"] else "No")
    if show_feedback and s.get("feedback"):
        st.subheader("Feedback")
        st.write(s["feedback"])
        st.caption(f"generated by: {s.get('feedback_provider')}")

    m = s.get("measurements") or {}
    rows = [{"measurement": k, "value": v.get("value"), "unit": v.get("unit"),
             "reliable": v.get("reliable"), "note": v.get("note", "")}
            for k, v in m.items() if isinstance(v, dict) and "value" in v]
    with st.expander("Deterministic measurements (from pose geometry)", expanded=False):
        st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)
        st.caption(f"primary angle: {m.get('primary_angle')} · sampled at {m.get('fps')} fps · duration {m.get('duration_s', 0):.1f}s")
        series = m.get("angle_series") or {}
        if series:
            prim = m.get("primary_angle")
            fig = go.Figure()
            for name in ([prim] if prim in series else []) + [n for n in ("trunk_lean",) if n in series]:
                fig.add_trace(go.Scatter(y=series[name], mode="lines", name=name))
            fig.update_layout(height=260, margin=dict(l=10, r=10, t=10, b=10), yaxis_title="degrees", xaxis_title="frame")
            st.plotly_chart(fig, use_container_width=True)

    obs = s.get("observations") or []
    st.subheader("Observations")
    if not obs:
        st.write("No observations flagged.")
    for o in obs:
        icon = {"review": "🔴", "attention": "🟠", "info": "🔵"}.get(o["severity"], "•")
        st.write(f"{icon} **{o['code'].replace('_', ' ')}** ({o['kind']}): {o['text']}")
        st.caption(str(o.get("evidence")))
    with st.expander("Class probabilities & pose quality"):
        st.json({"class_probabilities": s.get("class_probabilities"), "pose_quality": s.get("pose_quality"),
                 "model_versions": s.get("model_versions")})


def trend_chart(trend: dict):
    if not trend:
        st.write("No analyzed sessions yet.")
        return
    frames = []
    for code, pts in trend.items():
        for p in pts:
            frames.append({"exercise": f"{code} {p.get('exercise_name') or ''}", "date": p["date"], "score": p["score"]})
    df = pd.DataFrame(frames)
    fig = px.line(df, x="date", y="score", color="exercise", markers=True, range_y=[0, 100])
    fig.update_layout(height=320, margin=dict(l=10, r=10, t=10, b=10))
    st.plotly_chart(fig, use_container_width=True)


# ------------------------------------------------------------------ views
def patient_view():
    st.header("Patient view")
    disclaimer()
    name = st.text_input("Your name", value=st.session_state.get("patient_name", ""))
    if not name:
        st.stop()
    st.session_state["patient_name"] = name
    p = api("POST", "/patients", json={"name": name})
    pid = p["patient_id"]

    st.subheader("Upload an exercise video")
    up = st.file_uploader("Video file (mp4/mov)", type=["mp4", "mov", "m4v", "avi"])
    if up is not None and st.button("Analyze", type="primary"):
        with st.spinner("Extracting pose and analyzing movement..."):
            try:
                s = api("POST", "/sessions/analyze", files={"file": (up.name, up.getvalue(), up.type or "video/mp4")},
                        data={"patient_name": name, "audience": "patient"})
                st.session_state["last_session"] = s
            except Exception as exc:  # noqa: BLE001
                st.error(str(exc))
    if "last_session" in st.session_state:
        st.subheader("Latest result")
        show_session(st.session_state["last_session"])

    st.subheader("Progress over time")
    prog = api("GET", f"/patients/{pid}/progress")
    trend_chart(prog["quality_trend"])
    if prog["repeated_observations"]:
        st.write("Observations that keep coming back:")
        st.dataframe(pd.DataFrame(prog["repeated_observations"]), hide_index=True, use_container_width=True)

    st.subheader("Session history")
    sessions = api("GET", f"/patients/{pid}/sessions")
    if sessions:
        df = pd.DataFrame([{"id": s["id"], "date": s["created_at"], "status": s["status"], "exercise": s["exercise_name"],
                            "confidence": s["exercise_confidence"], "score": s["quality_score"], "review": s["needs_review"]}
                           for s in sessions])
        st.dataframe(df, hide_index=True, use_container_width=True)
        sid = st.selectbox("Open a session", df["id"].tolist())
        if sid:
            show_session(api("GET", f"/sessions/{sid}"))


def physio_view():
    st.header("Physiotherapist view")
    disclaimer()
    overview = api("GET", "/patients")
    st.subheader("Patient overview")
    if overview:
        st.dataframe(pd.DataFrame(overview), hide_index=True, use_container_width=True)
    else:
        st.write("No patients yet.")

    st.subheader("Sessions requiring review")
    queue = api("GET", "/review")
    if queue:
        st.dataframe(pd.DataFrame([{"session": s["id"], "patient": s["patient_id"], "date": s["created_at"],
                                    "exercise": s["exercise_name"], "score": s["quality_score"],
                                    "reasons": "; ".join(s.get("review_reasons") or [])} for s in queue]),
                     hide_index=True, use_container_width=True)
    else:
        st.write("Nothing waiting for review.")

    if not overview:
        return
    names = {f"{o['name']} (#{o['patient_id']})": o["patient_id"] for o in overview}
    choice = st.selectbox("Patient", list(names))
    pid = names[choice]
    prog = api("GET", f"/patients/{pid}/progress")
    st.subheader("Quality trends by exercise")
    trend_chart(prog["quality_trend"])
    st.subheader("Repeated observations")
    if prog["repeated_observations"]:
        st.dataframe(pd.DataFrame(prog["repeated_observations"]), hide_index=True, use_container_width=True)
    else:
        st.write("No repeated observations.")

    st.subheader("Recent sessions")
    sessions = api("GET", f"/patients/{pid}/sessions")
    if sessions:
        df = pd.DataFrame([{"id": s["id"], "date": s["created_at"], "status": s["status"], "exercise": s["exercise_name"],
                            "confidence": s["exercise_confidence"], "score": s["quality_score"], "review": s["needs_review"],
                            "note": s.get("clinician_note")} for s in sessions])
        st.dataframe(df, hide_index=True, use_container_width=True)
        sid = st.selectbox("Inspect session", df["id"].tolist())
        if sid:
            s = api("GET", f"/sessions/{sid}")
            show_session(s)
            note = st.text_area("Clinician note", value=s.get("clinician_note") or "")
            if st.button("Save note and mark reviewed"):
                api("POST", f"/sessions/{sid}/note", json={"note": note, "mark_reviewed": True})
                st.success("Saved.")
                st.rerun()


def main():
    st.sidebar.title("Home Physiotherapy Assistant")
    try:
        h = api("GET", "/health")
        st.sidebar.success("API connected" + ("" if h["models_loaded"] else " (models not loaded)"))
        if not h["models_loaded"]:
            st.sidebar.warning(h.get("analyzer_error"))
    except Exception as exc:  # noqa: BLE001
        st.sidebar.error(f"API not reachable at {API}: {exc}")
        st.stop()
    view = st.sidebar.radio("View", ["Patient", "Physiotherapist"])
    (patient_view if view == "Patient" else physio_view)()


main()
